
ALTER TABLE public.tenant_info
  ADD COLUMN IF NOT EXISTS birth_date date,
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS religion text,
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS passport_number text,
  ADD COLUMN IF NOT EXISTS emergency_name text,
  ADD COLUMN IF NOT EXISTS emergency_relation text,
  ADD COLUMN IF NOT EXISTS emergency_address text,
  ADD COLUMN IF NOT EXISTS previous_landlord_name text,
  ADD COLUMN IF NOT EXISTS previous_landlord_phone text,
  ADD COLUMN IF NOT EXISTS leave_reason text,
  ADD COLUMN IF NOT EXISTS current_landlord_name text,
  ADD COLUMN IF NOT EXISTS helper_name text,
  ADD COLUMN IF NOT EXISTS helper_nid text,
  ADD COLUMN IF NOT EXISTS helper_phone text,
  ADD COLUMN IF NOT EXISTS helper_address text,
  ADD COLUMN IF NOT EXISTS driver_name text,
  ADD COLUMN IF NOT EXISTS driver_nid text,
  ADD COLUMN IF NOT EXISTS beat_no text,
  ADD COLUMN IF NOT EXISTS ward_no text,
  ADD COLUMN IF NOT EXISTS holding_no text,
  ADD COLUMN IF NOT EXISTS road text,
  ADD COLUMN IF NOT EXISTS area text,
  ADD COLUMN IF NOT EXISTS post_code text;
