// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogurhyuwaurxxivwgqnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndXJoeXV3YXVyeHhpdndncW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NTM3MTUsImV4cCI6MjA5MzIyOTcxNX0.2R7u7F9_4bYEDxVJZkBzPLCXkph1sLMC92dOWYTMfsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});